"use client";
import { useMemo,useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import { defaultRules,records as seedRecords } from "@/lib/mock-data";
import { downloadHealthExcel } from "@/lib/excel";
import { ExamType,RuleSettings } from "@/lib/types";
const LOGO="https://raw.githubusercontent.com/dhdh09080/seongdongxi/main/gsenc_logo.png";
const typeLabel:Record<ExamType,string>={general:"일반",special:"특수",preplacement:"배치전"};

export default function Admin(){
 const records=seedRecords; const [query,setQuery]=useState(""); const [type,setType]=useState<"all"|ExamType>("all");
 const [rules,setRules]=useState<RuleSettings>(defaultRules); const [settingsOpen,setSettingsOpen]=useState(false); const [detail,setDetail]=useState<string|null>(null); const [toast,setToast]=useState("");
 const uploadUrl=typeof window==="undefined"?"https://example.com/upload":`${window.location.origin}/upload?site=070120`;
 const filtered=useMemo(()=>records.filter(r=>{const q=query.trim().toLowerCase();return(!q||[r.workerName,r.companyName,r.sourceFileName].some(x=>x.toLowerCase().includes(q)))&&(type==="all"||r.examType===type)}),[query,type]);
 const senior=records.filter(r=>r.age>=63), review=records.filter(r=>r.reviewStatus!=="ok");
 function copyLink(){navigator.clipboard?.writeText(uploadUrl);setToast("업로드 링크를 복사했습니다.");setTimeout(()=>setToast(""),1800)}
 function toggleHazard(h:string){setRules(r=>({...r,requiredHazards:r.requiredHazards.includes(h)?r.requiredHazards.filter(x=>x!==h):[...r.requiredHazards,h]}))}
 return <main className="admin-shell">
  <aside className="sidebar"><img src={LOGO} alt="GS건설" className="side-logo"/><nav><button className="active">▦ 대시보드</button><button>▤ 건강진단 결과</button><button>◫ 업로드 서류</button><button>⌂ 협력사 관리</button><button onClick={()=>setSettingsOpen(true)}>⚙ 검토 기준 설정</button></nav><div className="site-card"><small>현재 현장</small><strong>성동자이리버뷰(서울)</strong><span>070120</span></div></aside>
  <section className="admin-main">
   <header className="admin-header"><div><span className="eyebrow">GS HEALTH ADMIN</span><h1>건강진단 관리</h1><p>업로드된 서류를 검토하고 PMX 업로드용 엑셀을 생성합니다.</p></div><div className="header-actions"><button className="secondary-button" onClick={()=>setSettingsOpen(true)}>검토 기준</button><button className="primary-button" onClick={copyLink}>업로드 링크 공유</button></div></header>
   <div className="metric-grid"><article><small>오늘 업로드</small><strong>2</strong><span>건</span></article><article className="warning"><small>검토 필요</small><strong>{review.length}</strong><span>건</span></article><article><small>만 63세 이상</small><strong>{senior.length}</strong><span>명</span></article><article><small>협력사</small><strong>4</strong><span>개사</span></article></div>
   <div className="dashboard-grid">
    <section className="panel"><div className="panel-head"><div><h2>업로드 현황</h2><p>사람별 · 업체별로 결과와 원본 파일을 관리합니다.</p></div><div className="filters"><input placeholder="이름 · 업체 검색" value={query} onChange={e=>setQuery(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value as any)}><option value="all">전체 종류</option><option value="preplacement">배치전</option><option value="special">특수</option><option value="general">일반</option></select></div></div>
     <div className="table-wrap"><table><thead><tr><th>업로드</th><th>협력사</th><th>근로자</th><th>나이</th><th>검진종류</th><th>검진일</th><th>결과</th><th>상태</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.uploadDate.slice(5,16)}</td><td>{r.companyName}</td><td><b>{r.workerName}</b></td><td>{r.age}{r.age>=63&&<span className="senior-badge">63+</span>}</td><td>{typeLabel[r.examType]}</td><td>{r.examDate}</td><td>{r.resultCode}</td><td><span className={`status ${r.reviewStatus}`}>{r.reviewStatus==="ok"?"정상":r.reviewStatus==="review"?"확인필요":"재업로드"}</span></td><td><button className="text-button" onClick={()=>setDetail(r.id)}>보기</button></td></tr>)}</tbody></table></div>
    </section>
    <aside className="panel share-panel"><h2>업로드 QR</h2><p>현장 게시 또는 협력사 관리자에게 전달하세요.</p><div className="qr-box"><QRCodeSVG value={uploadUrl} size={164}/></div><code>{uploadUrl}</code><button className="secondary-button full" onClick={copyLink}>링크 복사</button><div className="pmx-card"><div><b>PMX 협력사 연동</b><small>협력사 코드·이름 자동 업데이트</small></div><button disabled>준비중</button></div></aside>
   </div>
   <section className="panel export-panel"><div><h2>PMX 업로드용 엑셀</h2><p>기존 양식의 코드값으로 배치전·특수·일반 결과를 각각 생성합니다.</p></div><div className="export-actions"><button onClick={()=>downloadHealthExcel("preplacement",records)}>배치전건강진단.xlsx</button><button onClick={()=>downloadHealthExcel("special",records)}>특수건강진단.xlsx</button><button onClick={()=>downloadHealthExcel("general",records)}>일반건강검진.xlsx</button></div></section>
   <section className="panel senior-panel"><div className="panel-head"><div><h2>만 63세 이상 근로자</h2><p>6개월 유효기간 규칙이 적용되는 대상입니다.</p></div></div><div className="senior-list">{senior.map(r=><article key={r.id}><div><strong>{r.workerName}</strong><span>{r.age}세</span></div><p>{r.companyName} · {typeLabel[r.examType]} · {r.examDate}</p>{r.issues.length>0&&<small>{r.issues[0]}</small>}</article>)}</div></section>
  </section>
  {settingsOpen&&<div className="modal-backdrop" onClick={()=>setSettingsOpen(false)}><section className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>검토 기준 설정</h2><button onClick={()=>setSettingsOpen(false)}>×</button></div><div className="form-grid two"><label>만 63세 미만 유효기간<input type="number" value={rules.under63Months} onChange={e=>setRules({...rules,under63Months:Number(e.target.value)})}/><span>개월</span></label><label>만 63세 이상 유효기간<input type="number" value={rules.over63Months} onChange={e=>setRules({...rules,over63Months:Number(e.target.value)})}/><span>개월</span></label></div><div className="setting-group"><b>배치전·특수 필수 유해인자</b><p>현장 특성에 따라 체크 제외 또는 추가할 수 있습니다.</p><div className="checkbox-grid">{["소음","분진","자외선","유기용제","야간작업"].map(h=><label key={h}><input type="checkbox" checked={rules.requiredHazards.includes(h)} onChange={()=>toggleHazard(h)}/>{h}</label>)}</div></div><label className="toggle-row"><span><b>R(재검) 시 2차 검진 결과 필수</b><small>2차 결과가 없으면 재업로드 요청</small></span><input type="checkbox" checked={rules.requireSecondaryForR} onChange={e=>setRules({...rules,requireSecondaryForR:e.target.checked})}/></label><button className="primary-button full large" onClick={()=>setSettingsOpen(false)}>저장</button></section></div>}
  {detail&&<div className="modal-backdrop" onClick={()=>setDetail(null)}><section className="modal detail-modal" onClick={e=>e.stopPropagation()}>{(()=>{const r=records.find(x=>x.id===detail)!;return <><div className="modal-head"><div><h2>{r.workerName} · {typeLabel[r.examType]}</h2><p>{r.companyName}</p></div><button onClick={()=>setDetail(null)}>×</button></div><div className="result-card"><div><small>검진일</small><b>{r.examDate}</b></div><div><small>결과</small><b>{r.resultCode} · {r.note}</b></div><div><small>판독 신뢰도</small><b>{Math.round(r.confidence*100)}%</b></div><div><small>원본 파일</small><b>{r.sourceFileName}</b></div></div>{r.issues.length?<div className="alert error"><b>확인이 필요합니다.</b>{r.issues.map(x=><p key={x}>• {x}</p>)}</div>:<div className="alert success">자동 검토 항목에 이상이 없습니다.</div>}<div className="button-row"><button className="secondary-button large">원본 다운로드</button><button className="primary-button large">검토 완료 처리</button></div></>})()}</section></div>}
  {toast&&<div className="toast">{toast}</div>}
 </main>
}
